### ISSUE TITLE
The link of the code and features is unavailable

### ISSUE THREAD

**Issue by tangzhenyu** [xSupervisedLearning/Rong360_feature_mining_1st_solution#1]
Hi, 

After reading your report about the contest, I found it's very useful for me.

As the Baiduyun link in your report about the code and features is unavailable, could you please reshare these content again.

I would be appreciated for your help.

**Comment by Terminator1306** [comment]
the url is available permanently, you could try it again. 
the code is as same as the code in github, i just did't put data up to gihub.

**Comment by Terminator1306** [comment]
the link in github is available permanently, which is https://pan.baidu.com/s/1vk_ASzdZUcLOFZmWFi_28g, password is qfb2

**Comment by tangzhenyu** [comment]
Understanding, thanks for your help.
