### ISSUE TITLE
关于关联分析的embedding

### ISSUE THREAD

**Issue by XueAdas** [xSupervisedLearning/Rong360_feature_mining_1st_solution#2]
您好！我是数据分析的初学者，这是个非常了不起的项目，您的项目给了我很大的帮助，但是我用OpenNE的deepwalk做的128维向量并不能复现您的实验结果，想请问一下您是如何去做的，我是拿data/graph_for_emb.txt去掉权重维度丢到OpenNE去训练，训练参数如您项目提供的信息相同

**Comment by Terminator1306** [comment]
不能复现是指的效果没有那么好吗？如果是效果不好也有可能是其他的问题吧，比如其他的特征、stacking之类的。我用的是deepwalk的源码，window size一定要设成5

**Comment by XueAdas** [comment]
> 不能复现是指的效果没有那么好吗？如果是效果不好也有可能是其他的问题吧，比如其他的特征、stacking之类的。我用的是deepwalk的源码，window size一定要设成5

是的，在单模型上比原项目结果低2到3个百分点，和不加embedding的准确度差不多。好的，我改成5试试，话说在deepwalk阶段有用到weight信息嘛，我在想是不是我丢掉权重信息导致的Orz

**Comment by Terminator1306** [comment]
你检查一下deepwalk训练出来的向量正确地加入到了样本中吗，deepwalk不需要weight，如果之前Window size不是5的话，影响挺大的

**Comment by XueAdas** [comment]
> 你检查一下deepwalk训练出来的向量正确地加入到了样本中吗，deepwalk不需要weight，如果之前Window size不是5的话，影响挺大的

好哒，十分感谢！之前window_size设置的是10,那感觉很有可能是这个原因了O_O
